version: '2'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: vapor
      POSTGRES_DB: vapor
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
  server:
    build:
      context: .
    depends_on:
      - db
      - redis
    ports:
      - '8000:8000'
