version: '2'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DB_HOST: db
  DB_NAME: vapor
  DB_USER: vapor
  DB_PASS: password

volumes:
  db_data:

services:
  db:
    image: postgres:11
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: vapor
      POSTGRES_DB: vapor
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: always
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
  server:
    build:
      context: .
     dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    environment:
      <<: *shared_environment
    ports:
      - 80:8080
